#!/usr/bin/env bash
# Build src/wasm/diff.wasm from native/diff.c (bare Clang/wasm-ld, no Emscripten).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

OUT_DIR="$ROOT/src/wasm"
mkdir -p "$OUT_DIR"

CLANG=""
for candidate in \
  "${WASI_SDK_PATH:+$WASI_SDK_PATH/bin/clang}" \
  /opt/homebrew/opt/llvm/bin/clang \
  /usr/local/opt/llvm/bin/clang \
  clang; do
  if [[ -n "$candidate" && -x "$candidate" ]]; then
    if "$candidate" --target=wasm32-unknown-unknown -c -x c /dev/null -o /dev/null 2>/dev/null; then
      CLANG="$candidate"
      break
    fi
  fi
done

if [[ -z "$CLANG" ]]; then
  echo "error: no clang with wasm32-unknown-unknown support found."
  echo "Install LLVM or wasi-sdk and set WASI_SDK_PATH."
  exit 1
fi

WASM_LD=""
for candidate in \
  "${WASI_SDK_PATH:+$WASI_SDK_PATH/bin/wasm-ld}" \
  "$(dirname "$CLANG")/wasm-ld" \
  wasm-ld; do
  if [[ -n "$candidate" && -x "$candidate" ]]; then
    WASM_LD="$candidate"
    break
  fi
done

if [[ -z "$WASM_LD" ]]; then
  echo "error: wasm-ld not found (install wasi-sdk or LLVM lld)."
  exit 1
fi

echo "Using CLANG=$CLANG"
echo "Using WASM_LD=$WASM_LD"

OBJ="$OUT_DIR/diff.o"
WASM="$OUT_DIR/diff.wasm"

"$CLANG" --target=wasm32-unknown-unknown -c -O3 native/diff.c -o "$OBJ"

"$WASM_LD" \
  -m wasm32 \
  --no-entry \
  --export-memory \
  --initial-memory=16777216 \
  --max-memory=2147483648 \
  --export=arena_bytes \
  --export=alloc_arena \
  --export=get_tokens_a_ptr \
  --export=get_tokens_b_ptr \
  --export=run_diff \
  --export=get_result_ops_ptr \
  --export=get_result_indices_ptr \
  --export=get_result_len \
  --export=get_result_keep_count \
  --export=get_result_insert_count \
  --export=get_result_delete_count \
  "$OBJ" -o "$WASM"

rm -f "$OBJ"
echo "Built $WASM ($(wc -c < "$WASM" | tr -d ' ') bytes)"

# Inline the wasm as base64 so the package works via `npm install` everywhere
# (Node, browsers, bundlers, Deno, Bun, edge) with zero configuration.
WASM_JS="$OUT_DIR/diff.wasm.js"
node -e '
  const fs = require("fs");
  const b64 = fs.readFileSync(process.argv[1]).toString("base64");
  const header =
    "// AUTO-GENERATED by scripts/build.sh — do not edit by hand.\n" +
    "// Inlined diff.wasm (base64) so the package works via `npm install` in Node,\n" +
    "// browsers, bundlers, Deno, Bun and edge runtimes with zero configuration.\n";
  fs.writeFileSync(process.argv[2], header + "export const wasmBase64 =\n  \x27" + b64 + "\x27;\n");
' "$WASM" "$WASM_JS"
echo "Inlined $WASM_JS ($(wc -c < "$WASM_JS" | tr -d ' ') bytes)"
